version: '3.8'

services:
  user-service:
    build:
      context: .
      dockerfile: ./services/user-service/Dockerfile
    volumes:
      - ./services/user-service:/usr/src/app/services/user-service  # Volume mount
      - ./shared:/usr/src/app/shared
    env_file:
      - ./services/user-service/.env
    ports:
      - "3001:3001"
    networks:
      - mynetwork

  account-service:
    build:
      context: .
      dockerfile: ./services/account-service/Dockerfile
    volumes:
      - ./services/account-service:/usr/src/app/services/account-service  # Volume mount
      - ./shared:/usr/src/app/shared
    env_file:
      - ./services/account-service/.env
    ports:
      - "3002:3002"
    networks:
      - mynetwork

  transaction-service:
    build:
      context: .
      dockerfile: ./services/transaction-service/Dockerfile
    volumes:
      - ./services/transaction-service:/usr/src/app/services/transaction-service  # Volume mount
      - ./shared:/usr/src/app/shared
    env_file:
      - ./services/transaction-service/.env
    ports:
      - "3003:3003"
    networks:
      - mynetwork

  payment-service:
    build:
      context: .
      dockerfile: ./services/payment-service/Dockerfile
    volumes:
      - ./services/payment-service:/usr/src/app/services/payment-service # Volume mount
      - ./shared:/usr/src/app/shared
    env_file:
      - ./services/payment-service/.env
    ports:
      - "3004:3004"
    networks:
      - mynetwork

  kyc-service:
    build:
      context: .
      dockerfile: ./services/kyc-service/Dockerfile
    volumes:
      - ./services/kyc-service:/usr/src/app/services/kyc-service  # Volume mount
      - ./shared:/usr/src/app/shared
    env_file:
      - ./services/kyc-service/.env
    ports:
      - "3005:3005"
    networks:
      - mynetwork

  notification-service:
    build:
      context: .
      dockerfile: ./services/notification-service/Dockerfile
    volumes:
      - ./services/notification-service:/usr/src/app/services/notification-service  # Volume mount
      - ./shared:/usr/src/app/shared
    env_file:
      - ./services/notification-service/.env
    ports:
      - "3006:3006"
    networks:
      - mynetwork

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - mynetwork

networks:
 mynetwork: