version: '3.8'

services:
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    env_file:
      - ./user-service/.env
    ports:
      - "3001:3000"
    depends_on:
      - mongodb
    networks:
      - mynetwork

  account-service:
    build:
      context: ./account-service
      dockerfile: Dockerfile
    env_file:
      - ./account-service/.env
    ports:
      - "3002:3000"
    depends_on:
      - mongodb
    networks:
      - mynetwork

  transaction-service:
    build:
      context: ./transaction-service
      dockerfile: Dockerfile
    env_file:
      - ./transaction-service/.env
    ports:
      - "3003:3000"
    depends_on:
      - mongodb
    networks:
      - mynetwork

  payment-service:
    build:
      context: ./payment-service
      dockerfile: Dockerfile
    env_file:
      - ./payment-service/.env
    ports:
      - "3004:3000"
    depends_on:
      - mongodb
    networks:
      - mynetwork

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - mynetwork

networks:
 mynetwork:

volumes:
 mongo-data: