version: '3.8'

services:
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    volumes:
      - ./user-service:/usr/src/app  # Volume mount
    env_file:
      - ./user-service/.env
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
    networks:
      - mynetwork

  account-service:
    build:
      context: ./account-service
      dockerfile: Dockerfile
    volumes:
      - ./account-service:/usr/src/app  # Volume mount
    env_file:
      - ./account-service/.env
    ports:
      - "3002:3002"
    depends_on:
      - mongodb
    networks:
      - mynetwork

  transaction-service:
    build:
      context: ./transaction-service
      dockerfile: Dockerfile
    volumes:
      - ./transaction-service:/usr/src/app  # Volume mount
    env_file:
      - ./transaction-service/.env
    ports:
      - "3003:3003"
    depends_on:
      - mongodb
    networks:
      - mynetwork

  payment-service:
    build:
      context: ./payment-service
      dockerfile: Dockerfile
    volumes:
      - ./payment-service:/usr/src/app  # Volume mount
    env_file:
      - ./payment-service/.env
    ports:
      - "3004:3004"
    depends_on:
      - mongodb
    networks:
      - mynetwork

  kyc-service:
    build:
      context: ./kyc-service
      dockerfile: Dockerfile
    volumes:
      - ./kyc-service:/usr/src/app  # Volume mount
    env_file:
      - ./kyc-service/.env
    ports:
      - "3005:3005"
    depends_on:
      - mongodb
    networks:
      - mynetwork

  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    volumes:
      - ./notification-service:/usr/src/app  # Volume mount
    env_file:
      - ./notification-service/.env
    ports:
      - "3006:3006"
    depends_on:
      - mongodb
    networks:
      - mynetwork

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - mynetwork

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - mynetwork

networks:
 mynetwork:

volumes:
 mongo-data: